package co.za.payu.ws;

import java.net.MalformedURLException;
import java.net.URISyntaxException;
import java.net.URI;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.jws.HandlerChain;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "EnterpriseAPISoapService", targetNamespace = "http://soap.api.controller.web.payjar.com/", wsdlLocation = "https://secure.payu.co.za/service/PayUAPI?wsdl")
@HandlerChain(file = "EnterpriseAPISoap_handler.xml")
public class EnterpriseAPISoapService extends Service
{
    private static final Logger log = LoggerFactory.getLogger(EnterpriseAPISoapService.class);
    private static final URL ENTERPRISEAPISOAPSERVICE_WSDL_LOCATION;
    private static final WebServiceException ENTERPRISEAPISOAPSERVICE_EXCEPTION;
    private static final QName ENTERPRISEAPISOAPSERVICE_QNAME = new QName("http://soap.api.controller.web.payjar.com/", "EnterpriseAPISoapService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URI("https://secure.payu.co.za/service/PayUAPI?wsdl").toURL();
        } catch (URISyntaxException | MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ENTERPRISEAPISOAPSERVICE_WSDL_LOCATION = url;
        ENTERPRISEAPISOAPSERVICE_EXCEPTION = e;
    }

    public EnterpriseAPISoapService() {
        super(__getWsdlLocation(), ENTERPRISEAPISOAPSERVICE_QNAME);
    }

    public EnterpriseAPISoapService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ENTERPRISEAPISOAPSERVICE_QNAME, features);
    }

    public EnterpriseAPISoapService(URL wsdlLocation) {
        super(wsdlLocation, ENTERPRISEAPISOAPSERVICE_QNAME);
    }

    public EnterpriseAPISoapService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ENTERPRISEAPISOAPSERVICE_QNAME, features);
    }

    public EnterpriseAPISoapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public EnterpriseAPISoapService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns EnterpriseAPISoap
     */
    @WebEndpoint(name = "EnterpriseAPISoapPort")
    public EnterpriseAPISoap getEnterpriseAPISoapPort() {
        return super.getPort(new QName("http://soap.api.controller.web.payjar.com/", "EnterpriseAPISoapPort"), EnterpriseAPISoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns EnterpriseAPISoap
     */
    @WebEndpoint(name = "EnterpriseAPISoapPort")
    public EnterpriseAPISoap getEnterpriseAPISoapPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://soap.api.controller.web.payjar.com/", "EnterpriseAPISoapPort"), EnterpriseAPISoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ENTERPRISEAPISOAPSERVICE_EXCEPTION!= null) {
            throw ENTERPRISEAPISOAPSERVICE_EXCEPTION;
        }
        return ENTERPRISEAPISOAPSERVICE_WSDL_LOCATION;
    }
}